branches:
  only:
  - master
language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: test
    install:
    - npm install
    script:
    - npm run lint
    - npm run build
  - stage: deploy
    if: type = push
    install:
    - npm install
    script:
    - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
    - npm run deploy
notifications:
  slack:
    secure: R4a5+1JjQM75z9vZuuwjGXaoXrReNXR5byIFFkm64BJdylm+syX/zQgqM9vvo44EPgEFDS+aMV9bXu4MAjftEZoK+zzabce+1LOgd19uYy7VpQhNGEvL6PXvxGAnpfv6wqY4lgvPtaRvrpE1FUZKDDptusO7c/WfbdXHn5Er/Ido2ghnUJKfgWX76UNub07NkO9TjujSC6Fuap8jKm6SqKajAhgDSNsjBERlXja5tKJZt3HR41lJf3Z/20mme6Hucpj9pAYA9FSey5CsydG8xPuHi/bmw52XzIhTrhG4pSzN8sZrHD+5T/1KvcsNuNtAHp3I4+e687HBx4dX/stuEuz1Nm3Tp93fztk99DxeFh2p+GjsN4XV4pc+clzpVWA2mABoXBBCketSluqNHO/EwOYVc5Tcl7XEa81f+11PepV5XD8Hueeur33zdM4qbineorITpzv2W5K6QPaRaEM0wRL1O65vI9BWM7/6Ey9R9obQaidc+13ICtoT6klldxstwiwiMdGfMA6YyNbu1VgnQO8Mj339CEXa0vjBzeWC6HyVFqA586xBW/2kcDdPg7NhRkMV5DCHQK9T2JpDuyKftqTOZf50ccG8eh5stoF2Tqwg2U1HDvjewwWPyBFI2ejEq18amPHeH71vgJcMcAqOXs3y+meyakrfw+4FZXrUUiY=
